<template>
    <div class="table-container">
      <table class="custom-table">
        <thead>
          <tr>
            <th>Syntax</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>.m-0</td>
          </tr>
          <tr>
            <td>.mx-0</td>
          </tr>
          <tr>
            <td>.my-0</td>
          </tr>
          <tr>
            <td>.ms-0</td>
          </tr>
          <tr>
            <td>.me-0</td>
          </tr>
          <tr>
            <td>.mt-0</td>
          </tr>
          <tr>
            <td>.mr-0</td>
          </tr>
          <tr>
            <td>.mb-0</td>
          </tr>
          <tr>
            <td>.ml-0</td>
          </tr>
          <tr>
            <td>.m</td>
          </tr>
          <tr>
            <td>.mx</td>
          </tr>
          <tr>
            <td>.my</td>
          </tr>
          <tr>
            <td>.ms</td>
          </tr>
          <tr>
            <td>.me</td>
          </tr>
          <tr>
            <td>.mt</td>
          </tr>
          <tr>
            <td>.mr</td>
          </tr>
          <tr>
            <td>.mb</td>
          </tr>
          <tr>
            <td>.ml</td>
          </tr>
          <tr>
            <td>.m-1</td>
          </tr>
          <tr>
            <td>.mx-1</td>
          </tr>
          <tr>
            <td>.my-1</td>
          </tr>
          <tr>
            <td>.ms-1</td>
          </tr>
          <tr>
            <td>.me-1</td>
          </tr>
          <tr>
            <td>.mt-1</td>
          </tr>
          <tr>
            <td>.mr-1</td>
          </tr>
          <tr>
            <td>.mb-1</td>
          </tr>
          <tr>
            <td>.ml-1</td>
          </tr>
          <tr>
            <td>.m-2</td>
          </tr>
          <tr>
            <td>.mx-2</td>
          </tr>
          <tr>
            <td>.my-2</td>
          </tr>
          <tr>
            <td>.ms-2</td>
          </tr>
          <tr>
            <td>.me-2</td>
          </tr>
          <tr>
            <td>.mt-2</td>
          </tr>
          <tr>
            <td>.mr-2</td>
          </tr>
          <tr>
            <td>.mb-2</td>
          </tr>
          <tr>
            <td>.ml-2</td>
          </tr>
          <tr>
            <td>.m-3</td>
          </tr>
          <tr>
            <td>.mx-3</td>
          </tr>
          <tr>
            <td>.my-3</td>
          </tr>
          <tr>
            <td>.ms-3</td>
          </tr>
          <tr>
            <td>.me-3</td>
          </tr>
          <tr>
            <td>.mt-3</td>
          </tr>
          <tr>
            <td>.mr-3</td>
          </tr>
          <tr>
            <td>.mb-3</td>
          </tr>
          <tr>
            <td>.ml-3</td>
          </tr>
          <tr>
            <td>.m-4</td>
          </tr>
          <tr>
            <td>.mx-4</td>
          </tr>
          <tr>
            <td>.my-4</td>
          </tr>
          <tr>
            <td>.ms-4</td>
          </tr>
          <tr>
            <td>.me-4</td>
          </tr>
          <tr>
            <td>.mt-4</td>
          </tr>
          <tr>
            <td>.mr-4</td>
          </tr>
          <tr>
            <td>.mb-4</td>
          </tr>
          <tr>
            <td>.ml-4</td>
          </tr>
          <tr>
            <td>.m-5</td>
          </tr>
          <tr>
            <td>.mx-5</td>
          </tr>
          <tr>
            <td>.my-5</td>
          </tr>
          <tr>
            <td>.ms-5</td>
          </tr>
          <tr>
            <td>.me-5</td>
          </tr>
          <tr>
            <td>.mt-5</td>
          </tr>
          <tr>
            <td>.mr-5</td>
          </tr>
          <tr>
            <td>.mb-5</td>
          </tr>
          <tr>
            <td>.ml-5</td>
          </tr>
          <tr>
            <td>.m-6</td>
          </tr>
          <tr>
            <td>.mx-6</td>
          </tr>
          <tr>
            <td>.my-6</td>
          </tr>
          <tr>
            <td>.ms-6</td>
          </tr>
          <tr>
            <td>.me-6</td>
          </tr>
          <tr>
            <td>.mt-6</td>
          </tr>
          <tr>
            <td>.mr-6</td>
          </tr>
          <tr>
            <td>.mb-6</td>
          </tr>
          <tr>
            <td>.ml-6</td>
          </tr>
          <tr>
            <td>.m-7</td>
          </tr>
          <tr>
            <td>.mx-7</td>
          </tr>
          <tr>
            <td>.my-7</td>
          </tr>
          <tr>
            <td>.ms-7</td>
          </tr>
          <tr>
            <td>.me-7</td>
          </tr>
          <tr>
            <td>.mt-7</td>
          </tr>
          <tr>
            <td>.mr-7</td>
          </tr>
          <tr>
            <td>.mb-7</td>
          </tr>
          <tr>
            <td>.ml-7</td>
          </tr>
          <tr>
            <td>.m-8</td>
          </tr>
          <tr>
            <td>.mx-8</td>
          </tr>
          <tr>
            <td>.my-8</td>
          </tr>
          <tr>
            <td>.ms-8</td>
          </tr>
          <tr>
            <td>.me-8</td>
          </tr>
          <tr>
            <td>.mt-8</td>
          </tr>
          <tr>
            <td>.mr-8</td>
          </tr>
          <tr>
            <td>.mb-8</td>
          </tr>
          <tr>
            <td>.ml-8</td>
          </tr>
          <tr>
            <td>.m-10</td>
          </tr>
          <tr>
            <td>.mx-10</td>
          </tr>
          <tr>
            <td>.my-10</td>
          </tr>
          <tr>
            <td>.ms-10</td>
          </tr>
          <tr>
            <td>.me-10</td>
          </tr>
          <tr>
            <td>.mt-10</td>
          </tr>
          <tr>
            <td>.mr-10</td>
          </tr>
          <tr>
            <td>.mb-10</td>
          </tr>
          <tr>
            <td>.ml-10</td>
          </tr>
          <tr>
            <td>.m-12</td>
          </tr>
          <tr>
            <td>.mx-12</td>
          </tr>
          <tr>
            <td>.my-12</td>
          </tr>
          <tr>
            <td>.ms-12</td>
          </tr>
          <tr>
            <td>.me-12</td>
          </tr>
          <tr>
            <td>.mt-12</td>
          </tr>
          <tr>
            <td>.mr-12</td>
          </tr>
          <tr>
            <td>.mb-12</td>
          </tr>
          <tr>
            <td>.ml-12</td>
          </tr>
          <tr>
            <td>.m-14</td>
          </tr>
          <tr>
            <td>.mx-14</td>
          </tr>
          <tr>
            <td>.my-14</td>
          </tr>
          <tr>
            <td>.ms-14</td>
          </tr>
          <tr>
            <td>.me-14</td>
          </tr>
          <tr>
            <td>.mt-14</td>
          </tr>
          <tr>
            <td>.mr-14</td>
          </tr>
          <tr>
            <td>.mb-14</td>
          </tr>
          <tr>
            <td>.ml-14</td>
          </tr>
          <tr>
            <td>.m-16</td>
          </tr>
          <tr>
            <td>.mx-16</td>
          </tr>
          <tr>
            <td>.my-16</td>
          </tr>
          <tr>
            <td>.ms-16</td>
          </tr>
          <tr>
            <td>.me-16</td>
          </tr>
          <tr>
            <td>.mt-16</td>
          </tr>
          <tr>
            <td>.mr-16</td>
          </tr>
          <tr>
            <td>.mb-16</td>
          </tr>
          <tr>
            <td>.ml-16</td>
          </tr>
          <tr>
            <td>.m-18</td>
          </tr>
          <tr>
            <td>.mx-18</td>
          </tr>
          <tr>
            <td>.my-18</td>
          </tr>
          <tr>
            <td>.ms-18</td>
          </tr>
          <tr>
            <td>.me-18</td>
          </tr>
          <tr>
            <td>.mt-18</td>
          </tr>
          <tr>
            <td>.mr-18</td>
          </tr>
          <tr>
            <td>.mb-18</td>
          </tr>
          <tr>
            <td>.ml-18</td>
          </tr>
          <tr>
            <td>.m-20</td>
          </tr>
          <tr>
            <td>.mx-20</td>
          </tr>
          <tr>
            <td>.my-20</td>
          </tr>
          <tr>
            <td>.ms-20</td>
          </tr>
          <tr>
            <td>.me-20</td>
          </tr>
          <tr>
            <td>.mt-20</td>
          </tr>
          <tr>
            <td>.mr-20</td>
          </tr>
          <tr>
            <td>.mb-20</td>
          </tr>
          <tr>
            <td>.ml-20</td>
          </tr>
          <tr>
            <td>.m-22</td>
          </tr>
          <tr>
            <td>.mx-22</td>
          </tr>
          <tr>
            <td>.my-22</td>
          </tr>
          <tr>
            <td>.ms-22</td>
          </tr>
          <tr>
            <td>.me-22</td>
          </tr>
          <tr>
            <td>.mt-22</td>
          </tr>
          <tr>
            <td>.mr-22</td>
          </tr>
          <tr>
            <td>.mb-22</td>
          </tr>
          <tr>
            <td>.ml-22</td>
          </tr>
          <tr>
            <td>.m-24</td>
          </tr>
          <tr>
            <td>.mx-24</td>
          </tr>
          <tr>
            <td>.my-24</td>
          </tr>
          <tr>
            <td>.ms-24</td>
          </tr>
          <tr>
            <td>.me-24</td>
          </tr>
          <tr>
            <td>.mt-24</td>
          </tr>
          <tr>
            <td>.mr-24</td>
          </tr>
          <tr>
            <td>.mb-24</td>
          </tr>
          <tr>
            <td>.ml-24</td>
          </tr>
          <tr>
            <td>.m-26</td>
          </tr>
          <tr>
            <td>.mx-26</td>
          </tr>
          <tr>
            <td>.my-26</td>
          </tr>
          <tr>
            <td>.ms-26</td>
          </tr>
          <tr>
            <td>.me-26</td>
          </tr>
          <tr>
            <td>.mt-26</td>
          </tr>
          <tr>
            <td>.mr-26</td>
          </tr>
          <tr>
            <td>.mb-26</td>
          </tr>
          <tr>
            <td>.ml-26</td>
          </tr>
          <tr>
            <td>.m-28</td>
          </tr>
          <tr>
            <td>.mx-28</td>
          </tr>
          <tr>
            <td>.my-28</td>
          </tr>
          <tr>
            <td>.ms-28</td>
          </tr>
          <tr>
            <td>.me-28</td>
          </tr>
          <tr>
            <td>.mt-28</td>
          </tr>
          <tr>
            <td>.mr-28</td>
          </tr>
          <tr>
            <td>.mb-28</td>
          </tr>
          <tr>
            <td>.ml-28</td>
          </tr>
          <tr>
            <td>.m-30</td>
          </tr>
          <tr>
            <td>.mx-30</td>
          </tr>
          <tr>
            <td>.my-30</td>
          </tr>
          <tr>
            <td>.ms-30</td>
          </tr>
          <tr>
            <td>.me-30</td>
          </tr>
          <tr>
            <td>.mt-30</td>
          </tr>
          <tr>
            <td>.mr-30</td>
          </tr>
          <tr>
            <td>.mb-30</td>
          </tr>
          <tr>
            <td>.ml-30</td>
          </tr>
          <tr>
            <td>.m-32</td>
          </tr>
          <tr>
            <td>.mx-32</td>
          </tr>
          <tr>
            <td>.my-32</td>
          </tr>
          <tr>
            <td>.ms-32</td>
          </tr>
          <tr>
            <td>.me-32</td>
          </tr>
          <tr>
            <td>.mt-32</td>
          </tr>
          <tr>
            <td>.mr-32</td>
          </tr>
          <tr>
            <td>.mb-32</td>
          </tr>
          <tr>
            <td>.ml-32</td>
          </tr>
          <tr>
            <td>.m-34</td>
          </tr>
          <tr>
            <td>.mx-34</td>
          </tr>
          <tr>
            <td>.my-34</td>
          </tr>
          <tr>
            <td>.ms-34</td>
          </tr>
          <tr>
            <td>.me-34</td>
          </tr>
          <tr>
            <td>.mt-34</td>
          </tr>
          <tr>
            <td>.mr-34</td>
          </tr>
          <tr>
            <td>.mb-34</td>
          </tr>
          <tr>
            <td>.ml-34</td>
          </tr>
          <tr>
            <td>.m-36</td>
          </tr>
          <tr>
            <td>.mx-36</td>
          </tr>
          <tr>
            <td>.my-36</td>
          </tr>
          <tr>
            <td>.ms-36</td>
          </tr>
          <tr>
            <td>.me-36</td>
          </tr>
          <tr>
            <td>.mt-36</td>
          </tr>
          <tr>
            <td>.mr-36</td>
          </tr>
          <tr>
            <td>.mb-36</td>
          </tr>
          <tr>
            <td>.ml-36</td>
          </tr>
          <tr>
            <td>.m-38</td>
          </tr>
          <tr>
            <td>.mx-38</td>
          </tr>
          <tr>
            <td>.my-38</td>
          </tr>
          <tr>
            <td>.ms-38</td>
          </tr>
          <tr>
            <td>.me-38</td>
          </tr>
          <tr>
            <td>.mt-38</td>
          </tr>
          <tr>
            <td>.mr-38</td>
          </tr>
          <tr>
            <td>.mb-38</td>
          </tr>
          <tr>
            <td>.ml-38</td>
          </tr>
          <tr>
            <td>.m-40</td>
          </tr>
          <tr>
            <td>.mx-40</td>
          </tr>
          <tr>
            <td>.my-40</td>
          </tr>
          <tr>
            <td>.ms-40</td>
          </tr>
          <tr>
            <td>.me-40</td>
          </tr>
          <tr>
            <td>.mt-40</td>
          </tr>
          <tr>
            <td>.mr-40</td>
          </tr>
          <tr>
            <td>.mb-40</td>
          </tr>
          <tr>
            <td>.ml-40</td>
          </tr>
          <tr>
            <td>.m-42</td>
          </tr>
          <tr>
            <td>.mx-42</td>
          </tr>
          <tr>
            <td>.my-42</td>
          </tr>
          <tr>
            <td>.ms-42</td>
          </tr>
          <tr>
            <td>.me-42</td>
          </tr>
          <tr>
            <td>.mt-42</td>
          </tr>
          <tr>
            <td>.mr-42</td>
          </tr>
          <tr>
            <td>.mb-42</td>
          </tr>
          <tr>
            <td>.ml-42</td>
          </tr>
          <tr>
            <td>.m-44</td>
          </tr>
          <tr>
            <td>.mx-44</td>
          </tr>
          <tr>
            <td>.my-44</td>
          </tr>
          <tr>
            <td>.ms-44</td>
          </tr>
          <tr>
            <td>.me-44</td>
          </tr>
          <tr>
            <td>.mt-44</td>
          </tr>
          <tr>
            <td>.mr-44</td>
          </tr>
          <tr>
            <td>.mb-44</td>
          </tr>
          <tr>
            <td>.ml-44</td>
          </tr>
          <tr>
            <td>.m-46</td>
          </tr>
          <tr>
            <td>.mx-46</td>
          </tr>
          <tr>
            <td>.my-46</td>
          </tr>
          <tr>
            <td>.ms-46</td>
          </tr>
          <tr>
            <td>.me-46</td>
          </tr>
          <tr>
            <td>.mt-46</td>
          </tr>
          <tr>
            <td>.mr-46</td>
          </tr>
          <tr>
            <td>.mb-46</td>
          </tr>
          <tr>
            <td>.ml-46</td>
          </tr>
          <tr>
            <td>.m-48</td>
          </tr>
          <tr>
            <td>.mx-48</td>
          </tr>
          <tr>
            <td>.my-48</td>
          </tr>
          <tr>
            <td>.ms-48</td>
          </tr>
          <tr>
            <td>.me-48</td>
          </tr>
          <tr>
            <td>.mt-48</td>
          </tr>
          <tr>
            <td>.mr-48</td>
          </tr>
          <tr>
            <td>.mb-48</td>
          </tr>
          <tr>
            <td>.ml-48</td>
          </tr>
          <tr>
            <td>.m-50</td>
          </tr>
          <tr>
            <td>.mx-50</td>
          </tr>
          <tr>
            <td>.my-50</td>
          </tr>
          <tr>
            <td>.ms-50</td>
          </tr>
          <tr>
            <td>.me-50</td>
          </tr>
          <tr>
            <td>.mt-50</td>
          </tr>
          <tr>
            <td>.mr-50</td>
          </tr>
          <tr>
            <td>.mb-50</td>
          </tr>
          <tr>
            <td>.ml-50</td>
          </tr>
          <tr>
            <td>.m-52</td>
          </tr>
          <tr>
            <td>.mx-52</td>
          </tr>
          <tr>
            <td>.my-52</td>
          </tr>
          <tr>
            <td>.ms-52</td>
          </tr>
          <tr>
            <td>.me-52</td>
          </tr>
          <tr>
            <td>.mt-52</td>
          </tr>
          <tr>
            <td>.mr-52</td>
          </tr>
          <tr>
            <td>.mb-52</td>
          </tr>
          <tr>
            <td>.ml-52</td>
          </tr>
          <tr>
            <td>.m-54</td>
          </tr>
          <tr>
            <td>.mx-54</td>
          </tr>
          <tr>
            <td>.my-54</td>
          </tr>
          <tr>
            <td>.ms-54</td>
          </tr>
          <tr>
            <td>.me-54</td>
          </tr>
          <tr>
            <td>.mt-54</td>
          </tr>
          <tr>
            <td>.mr-54</td>
          </tr>
          <tr>
            <td>.mb-54</td>
          </tr>
          <tr>
            <td>.ml-54</td>
          </tr>
          <tr>
            <td>.m-56</td>
          </tr>
          <tr>
            <td>.mx-56</td>
          </tr>
          <tr>
            <td>.my-56</td>
          </tr>
          <tr>
            <td>.ms-56</td>
          </tr>
          <tr>
            <td>.me-56</td>
          </tr>
          <tr>
            <td>.mt-56</td>
          </tr>
          <tr>
            <td>.mr-56</td>
          </tr>
          <tr>
            <td>.mb-56</td>
          </tr>
          <tr>
            <td>.ml-56</td>
          </tr>
          <tr>
            <td>.m-58</td>
          </tr>
          <tr>
            <td>.mx-58</td>
          </tr>
          <tr>
            <td>.my-58</td>
          </tr>
          <tr>
            <td>.ms-58</td>
          </tr>
          <tr>
            <td>.me-58</td>
          </tr>
          <tr>
            <td>.mt-58</td>
          </tr>
          <tr>
            <td>.mr-58</td>
          </tr>
          <tr>
            <td>.mb-58</td>
          </tr>
          <tr>
            <td>.ml-58</td>
          </tr>
          <tr>
            <td>.m-auto</td>
          </tr>
          <tr>
            <td>.mx-auto</td>
          </tr>
          <tr>
            <td>.my-auto</td>
          </tr>
          <tr>
            <td>.ms-auto</td>
          </tr>
          <tr>
            <td>.me-auto</td>
          </tr>
          <tr>
            <td>.mt-auto</td>
          </tr>
          <tr>
            <td>.mr-auto</td>
          </tr>
          <tr>
            <td>.mb-auto</td>
          </tr>
          <tr>
            <td>.ml-auto</td>
          </tr>
        </tbody>
      </table>
    </div>
  </template>
  
  <style scoped>
  .table-container {
    margin: 20px;
    max-height: 300px;
    overflow-y: auto;
  }
  
  .custom-table {
    width: 100%;
    border-collapse: collapse;
  }
  
  .custom-table th,
  .custom-table td {
    padding: 10px;
    text-align: center;
  }

  .custom-table tr {
    border-bottom: 1px solid rgb(85, 85, 85);
  }
  
  .custom-table tr:not(:last-child) td {
    border: none;
  }

  @media only screen and (max-width: 420px) {
    .table-container {
      margin: 20px;
      max-height: 200px;
      overflow-y: auto;
    }
  }
  </style>
  