<template>
    <div class="table-container">
      <table class="custom-table">
        <thead>
          <tr>
            <th>Syntax</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>.p-0</td>
          </tr>
          <tr>
            <td>.px-0</td>
          </tr>
          <tr>
            <td>.py-0</td>
          </tr>
          <tr>
            <td>.ps-0</td>
          </tr>
          <tr>
            <td>.pe-0</td>
          </tr>
          <tr>
            <td>.pt-0</td>
          </tr>
          <tr>
            <td>.pr-0</td>
          </tr>
          <tr>
            <td>.pb-0</td>
          </tr>
          <tr>
            <td>.pl-0</td>
          </tr>
          <tr>
            <td>.p</td>
          </tr>
          <tr>
            <td>.px</td>
          </tr>
          <tr>
            <td>.py</td>
          </tr>
          <tr>
            <td>.ps</td>
          </tr>
          <tr>
            <td>.pe</td>
          </tr>
          <tr>
            <td>.pt</td>
          </tr>
          <tr>
            <td>.pr</td>
          </tr>
          <tr>
            <td>.pb</td>
          </tr>
          <tr>
            <td>.pl</td>
          </tr>
          <tr>
            <td>.p-1</td>
          </tr>
          <tr>
            <td>.px-1</td>
          </tr>
          <tr>
            <td>.py-1</td>
          </tr>
          <tr>
            <td>.ps-1</td>
          </tr>
          <tr>
            <td>.pe-1</td>
          </tr>
          <tr>
            <td>.pt-1</td>
          </tr>
          <tr>
            <td>.pr-1</td>
          </tr>
          <tr>
            <td>.pb-1</td>
          </tr>
          <tr>
            <td>.pl-1</td>
          </tr>
          <tr>
            <td>.p-2</td>
          </tr>
          <tr>
            <td>.px-2</td>
          </tr>
          <tr>
            <td>.py-2</td>
          </tr>
          <tr>
            <td>.ps-2</td>
          </tr>
          <tr>
            <td>.pe-2</td>
          </tr>
          <tr>
            <td>.pt-2</td>
          </tr>
          <tr>
            <td>.pr-2</td>
          </tr>
          <tr>
            <td>.pb-2</td>
          </tr>
          <tr>
            <td>.pl-2</td>
          </tr>
          <tr>
            <td>.p-3</td>
          </tr>
          <tr>
            <td>.px-3</td>
          </tr>
          <tr>
            <td>.py-3</td>
          </tr>
          <tr>
            <td>.ps-3</td>
          </tr>
          <tr>
            <td>.pe-3</td>
          </tr>
          <tr>
            <td>.pt-3</td>
          </tr>
          <tr>
            <td>.pr-3</td>
          </tr>
          <tr>
            <td>.pb-3</td>
          </tr>
          <tr>
            <td>.pl-3</td>
          </tr>
          <tr>
            <td>.p-4</td>
          </tr>
          <tr>
            <td>.px-4</td>
          </tr>
          <tr>
            <td>.py-4</td>
          </tr>
          <tr>
            <td>.ps-4</td>
          </tr>
          <tr>
            <td>.pe-4</td>
          </tr>
          <tr>
            <td>.pt-4</td>
          </tr>
          <tr>
            <td>.pr-4</td>
          </tr>
          <tr>
            <td>.pb-4</td>
          </tr>
          <tr>
            <td>.pl-4</td>
          </tr>
          <tr>
            <td>.p-5</td>
          </tr>
          <tr>
            <td>.px-5</td>
          </tr>
          <tr>
            <td>.py-5</td>
          </tr>
          <tr>
            <td>.ps-5</td>
          </tr>
          <tr>
            <td>.pe-5</td>
          </tr>
          <tr>
            <td>.pt-5</td>
          </tr>
          <tr>
            <td>.pr-5</td>
          </tr>
          <tr>
            <td>.pb-5</td>
          </tr>
          <tr>
            <td>.pl-5</td>
          </tr>
          <tr>
            <td>.p-6</td>
          </tr>
          <tr>
            <td>.px-6</td>
          </tr>
          <tr>
            <td>.py-6</td>
          </tr>
          <tr>
            <td>.ps-6</td>
          </tr>
          <tr>
            <td>.pe-6</td>
          </tr>
          <tr>
            <td>.pt-6</td>
          </tr>
          <tr>
            <td>.pr-6</td>
          </tr>
          <tr>
            <td>.pb-6</td>
          </tr>
          <tr>
            <td>.pl-6</td>
          </tr>
          <tr>
            <td>.p-7</td>
          </tr>
          <tr>
            <td>.px-7</td>
          </tr>
          <tr>
            <td>.py-7</td>
          </tr>
          <tr>
            <td>.ps-7</td>
          </tr>
          <tr>
            <td>.pe-7</td>
          </tr>
          <tr>
            <td>.pt-7</td>
          </tr>
          <tr>
            <td>.pr-7</td>
          </tr>
          <tr>
            <td>.pb-7</td>
          </tr>
          <tr>
            <td>.pl-7</td>
          </tr>
          <tr>
            <td>.p-8</td>
          </tr>
          <tr>
            <td>.px-8</td>
          </tr>
          <tr>
            <td>.py-8</td>
          </tr>
          <tr>
            <td>.ps-8</td>
          </tr>
          <tr>
            <td>.pe-8</td>
          </tr>
          <tr>
            <td>.pt-8</td>
          </tr>
          <tr>
            <td>.pr-8</td>
          </tr>
          <tr>
            <td>.pb-8</td>
          </tr>
          <tr>
            <td>.pl-8</td>
          </tr>
          <tr>
            <td>.p-10</td>
          </tr>
          <tr>
            <td>.px-10</td>
          </tr>
          <tr>
            <td>.py-10</td>
          </tr>
          <tr>
            <td>.ps-10</td>
          </tr>
          <tr>
            <td>.pe-10</td>
          </tr>
          <tr>
            <td>.pt-10</td>
          </tr>
          <tr>
            <td>.pr-10</td>
          </tr>
          <tr>
            <td>.pb-10</td>
          </tr>
          <tr>
            <td>.pl-10</td>
          </tr>
          <tr>
            <td>.p-12</td>
          </tr>
          <tr>
            <td>.px-12</td>
          </tr>
          <tr>
            <td>.py-12</td>
          </tr>
          <tr>
            <td>.ps-12</td>
          </tr>
          <tr>
            <td>.pe-12</td>
          </tr>
          <tr>
            <td>.pt-12</td>
          </tr>
          <tr>
            <td>.pr-12</td>
          </tr>
          <tr>
            <td>.pb-12</td>
          </tr>
          <tr>
            <td>.pl-12</td>
          </tr>
          <tr>
            <td>.p-14</td>
          </tr>
          <tr>
            <td>.px-14</td>
          </tr>
          <tr>
            <td>.py-14</td>
          </tr>
          <tr>
            <td>.ps-14</td>
          </tr>
          <tr>
            <td>.pe-14</td>
          </tr>
          <tr>
            <td>.pt-14</td>
          </tr>
          <tr>
            <td>.pr-14</td>
          </tr>
          <tr>
            <td>.pb-14</td>
          </tr>
          <tr>
            <td>.pl-14</td>
          </tr>
          <tr>
            <td>.p-16</td>
          </tr>
          <tr>
            <td>.px-16</td>
          </tr>
          <tr>
            <td>.py-16</td>
          </tr>
          <tr>
            <td>.ps-16</td>
          </tr>
          <tr>
            <td>.pe-16</td>
          </tr>
          <tr>
            <td>.pt-16</td>
          </tr>
          <tr>
            <td>.pr-16</td>
          </tr>
          <tr>
            <td>.pb-16</td>
          </tr>
          <tr>
            <td>.pl-16</td>
          </tr>
          <tr>
            <td>.p-18</td>
          </tr>
          <tr>
            <td>.px-18</td>
          </tr>
          <tr>
            <td>.py-18</td>
          </tr>
          <tr>
            <td>.ps-18</td>
          </tr>
          <tr>
            <td>.pe-18</td>
          </tr>
          <tr>
            <td>.pt-18</td>
          </tr>
          <tr>
            <td>.pr-18</td>
          </tr>
          <tr>
            <td>.pb-18</td>
          </tr>
          <tr>
            <td>.pl-18</td>
          </tr>
          <tr>
            <td>.p-20</td>
          </tr>
          <tr>
            <td>.px-20</td>
          </tr>
          <tr>
            <td>.py-20</td>
          </tr>
          <tr>
            <td>.ps-20</td>
          </tr>
          <tr>
            <td>.pe-20</td>
          </tr>
          <tr>
            <td>.pt-20</td>
          </tr>
          <tr>
            <td>.pr-20</td>
          </tr>
          <tr>
            <td>.pb-20</td>
          </tr>
          <tr>
            <td>.pl-20</td>
          </tr>
          <tr>
            <td>.p-22</td>
          </tr>
          <tr>
            <td>.px-22</td>
          </tr>
          <tr>
            <td>.py-22</td>
          </tr>
          <tr>
            <td>.ps-22</td>
          </tr>
          <tr>
            <td>.pe-22</td>
          </tr>
          <tr>
            <td>.pt-22</td>
          </tr>
          <tr>
            <td>.pr-22</td>
          </tr>
          <tr>
            <td>.pb-22</td>
          </tr>
          <tr>
            <td>.pl-22</td>
          </tr>
          <tr>
            <td>.p-24</td>
          </tr>
          <tr>
            <td>.px-24</td>
          </tr>
          <tr>
            <td>.py-24</td>
          </tr>
          <tr>
            <td>.ps-24</td>
          </tr>
          <tr>
            <td>.pe-24</td>
          </tr>
          <tr>
            <td>.pt-24</td>
          </tr>
          <tr>
            <td>.pr-24</td>
          </tr>
          <tr>
            <td>.pb-24</td>
          </tr>
          <tr>
            <td>.pl-24</td>
          </tr>
          <tr>
            <td>.p-26</td>
          </tr>
          <tr>
            <td>.px-26</td>
          </tr>
          <tr>
            <td>.py-26</td>
          </tr>
          <tr>
            <td>.ps-26</td>
          </tr>
          <tr>
            <td>.pe-26</td>
          </tr>
          <tr>
            <td>.pt-26</td>
          </tr>
          <tr>
            <td>.pr-26</td>
          </tr>
          <tr>
            <td>.pb-26</td>
          </tr>
          <tr>
            <td>.pl-26</td>
          </tr>
          <tr>
            <td>.p-28</td>
          </tr>
          <tr>
            <td>.px-28</td>
          </tr>
          <tr>
            <td>.py-28</td>
          </tr>
          <tr>
            <td>.ps-28</td>
          </tr>
          <tr>
            <td>.pe-28</td>
          </tr>
          <tr>
            <td>.pt-28</td>
          </tr>
          <tr>
            <td>.pr-28</td>
          </tr>
          <tr>
            <td>.pb-28</td>
          </tr>
          <tr>
            <td>.pl-28</td>
          </tr>
          <tr>
            <td>.p-30</td>
          </tr>
          <tr>
            <td>.px-30</td>
          </tr>
          <tr>
            <td>.py-30</td>
          </tr>
          <tr>
            <td>.ps-30</td>
          </tr>
          <tr>
            <td>.pe-30</td>
          </tr>
          <tr>
            <td>.pt-30</td>
          </tr>
          <tr>
            <td>.pr-30</td>
          </tr>
          <tr>
            <td>.pb-30</td>
          </tr>
          <tr>
            <td>.pl-30</td>
          </tr>
          <tr>
            <td>.p-32</td>
          </tr>
          <tr>
            <td>.px-32</td>
          </tr>
          <tr>
            <td>.py-32</td>
          </tr>
          <tr>
            <td>.ps-32</td>
          </tr>
          <tr>
            <td>.pe-32</td>
          </tr>
          <tr>
            <td>.pt-32</td>
          </tr>
          <tr>
            <td>.pr-32</td>
          </tr>
          <tr>
            <td>.pb-32</td>
          </tr>
          <tr>
            <td>.pl-32</td>
          </tr>
          <tr>
            <td>.p-34</td>
          </tr>
          <tr>
            <td>.px-34</td>
          </tr>
          <tr>
            <td>.py-34</td>
          </tr>
          <tr>
            <td>.ps-34</td>
          </tr>
          <tr>
            <td>.pe-34</td>
          </tr>
          <tr>
            <td>.pt-34</td>
          </tr>
          <tr>
            <td>.pr-34</td>
          </tr>
          <tr>
            <td>.pb-34</td>
          </tr>
          <tr>
            <td>.pl-34</td>
          </tr>
          <tr>
            <td>.p-36</td>
          </tr>
          <tr>
            <td>.px-36</td>
          </tr>
          <tr>
            <td>.py-36</td>
          </tr>
          <tr>
            <td>.ps-36</td>
          </tr>
          <tr>
            <td>.pe-36</td>
          </tr>
          <tr>
            <td>.pt-36</td>
          </tr>
          <tr>
            <td>.pr-36</td>
          </tr>
          <tr>
            <td>.pb-36</td>
          </tr>
          <tr>
            <td>.pl-36</td>
          </tr>
          <tr>
            <td>.p-38</td>
          </tr>
          <tr>
            <td>.px-38</td>
          </tr>
          <tr>
            <td>.py-38</td>
          </tr>
          <tr>
            <td>.ps-38</td>
          </tr>
          <tr>
            <td>.pe-38</td>
          </tr>
          <tr>
            <td>.pt-38</td>
          </tr>
          <tr>
            <td>.pr-38</td>
          </tr>
          <tr>
            <td>.pb-38</td>
          </tr>
          <tr>
            <td>.pl-38</td>
          </tr>
          <tr>
            <td>.p-40</td>
          </tr>
          <tr>
            <td>.px-40</td>
          </tr>
          <tr>
            <td>.py-40</td>
          </tr>
          <tr>
            <td>.ps-40</td>
          </tr>
          <tr>
            <td>.pe-40</td>
          </tr>
          <tr>
            <td>.pt-40</td>
          </tr>
          <tr>
            <td>.pr-40</td>
          </tr>
          <tr>
            <td>.pb-40</td>
          </tr>
          <tr>
            <td>.pl-40</td>
          </tr>
          <tr>
            <td>.p-42</td>
          </tr>
          <tr>
            <td>.px-42</td>
          </tr>
          <tr>
            <td>.py-42</td>
          </tr>
          <tr>
            <td>.ps-42</td>
          </tr>
          <tr>
            <td>.pe-42</td>
          </tr>
          <tr>
            <td>.pt-42</td>
          </tr>
          <tr>
            <td>.pr-42</td>
          </tr>
          <tr>
            <td>.pb-42</td>
          </tr>
          <tr>
            <td>.pl-42</td>
          </tr>
          <tr>
            <td>.p-44</td>
          </tr>
          <tr>
            <td>.px-44</td>
          </tr>
          <tr>
            <td>.py-44</td>
          </tr>
          <tr>
            <td>.ps-44</td>
          </tr>
          <tr>
            <td>.pe-44</td>
          </tr>
          <tr>
            <td>.pt-44</td>
          </tr>
          <tr>
            <td>.pr-44</td>
          </tr>
          <tr>
            <td>.pb-44</td>
          </tr>
          <tr>
            <td>.pl-44</td>
          </tr>
          <tr>
            <td>.p-46</td>
          </tr>
          <tr>
            <td>.px-46</td>
          </tr>
          <tr>
            <td>.py-46</td>
          </tr>
          <tr>
            <td>.ps-46</td>
          </tr>
          <tr>
            <td>.pe-46</td>
          </tr>
          <tr>
            <td>.pt-46</td>
          </tr>
          <tr>
            <td>.pr-46</td>
          </tr>
          <tr>
            <td>.pb-46</td>
          </tr>
          <tr>
            <td>.pl-46</td>
          </tr>
          <tr>
            <td>.p-48</td>
          </tr>
          <tr>
            <td>.px-48</td>
          </tr>
          <tr>
            <td>.py-48</td>
          </tr>
          <tr>
            <td>.ps-48</td>
          </tr>
          <tr>
            <td>.pe-48</td>
          </tr>
          <tr>
            <td>.pt-48</td>
          </tr>
          <tr>
            <td>.pr-48</td>
          </tr>
          <tr>
            <td>.pb-48</td>
          </tr>
          <tr>
            <td>.pl-48</td>
          </tr>
          <tr>
            <td>.p-50</td>
          </tr>
          <tr>
            <td>.px-50</td>
          </tr>
          <tr>
            <td>.py-50</td>
          </tr>
          <tr>
            <td>.ps-50</td>
          </tr>
          <tr>
            <td>.pe-50</td>
          </tr>
          <tr>
            <td>.pt-50</td>
          </tr>
          <tr>
            <td>.pr-50</td>
          </tr>
          <tr>
            <td>.pb-50</td>
          </tr>
          <tr>
            <td>.pl-50</td>
          </tr>
          <tr>
            <td>.p-52</td>
          </tr>
          <tr>
            <td>.px-52</td>
          </tr>
          <tr>
            <td>.py-52</td>
          </tr>
          <tr>
            <td>.ps-52</td>
          </tr>
          <tr>
            <td>.pe-52</td>
          </tr>
          <tr>
            <td>.pt-52</td>
          </tr>
          <tr>
            <td>.pr-52</td>
          </tr>
          <tr>
            <td>.pb-52</td>
          </tr>
          <tr>
            <td>.pl-52</td>
          </tr>
          <tr>
            <td>.p-54</td>
          </tr>
          <tr>
            <td>.px-54</td>
          </tr>
          <tr>
            <td>.py-54</td>
          </tr>
          <tr>
            <td>.ps-54</td>
          </tr>
          <tr>
            <td>.pe-54</td>
          </tr>
          <tr>
            <td>.pt-54</td>
          </tr>
          <tr>
            <td>.pr-54</td>
          </tr>
          <tr>
            <td>.pb-54</td>
          </tr>
          <tr>
            <td>.pl-54</td>
          </tr>
          <tr>
            <td>.p-56</td>
          </tr>
          <tr>
            <td>.px-56</td>
          </tr>
          <tr>
            <td>.py-56</td>
          </tr>
          <tr>
            <td>.ps-56</td>
          </tr>
          <tr>
            <td>.pe-56</td>
          </tr>
          <tr>
            <td>.pt-56</td>
          </tr>
          <tr>
            <td>.pr-56</td>
          </tr>
          <tr>
            <td>.pb-56</td>
          </tr>
          <tr>
            <td>.pl-56</td>
          </tr>
          <tr>
            <td>.p-58</td>
          </tr>
          <tr>
            <td>.px-58</td>
          </tr>
          <tr>
            <td>.py-58</td>
          </tr>
          <tr>
            <td>.ps-58</td>
          </tr>
          <tr>
            <td>.pe-58</td>
          </tr>
          <tr>
            <td>.pt-58</td>
          </tr>
          <tr>
            <td>.pr-58</td>
          </tr>
          <tr>
            <td>.pb-58</td>
          </tr>
          <tr>
            <td>.pl-58</td>
          </tr>
          <tr>
            <td>.p-auto</td>
          </tr>
          <tr>
            <td>.px-auto</td>
          </tr>
          <tr>
            <td>.py-auto</td>
          </tr>
          <tr>
            <td>.ps-auto</td>
          </tr>
          <tr>
            <td>.pe-auto</td>
          </tr>
          <tr>
            <td>.pt-auto</td>
          </tr>
          <tr>
            <td>.pr-auto</td>
          </tr>
          <tr>
            <td>.pb-auto</td>
          </tr>
          <tr>
            <td>.pl-auto</td>
          </tr>
        </tbody>
      </table>
    </div>
  </template>
  
  <style scoped>
  .table-container {
    margin: 20px;
    max-height: 300px;
    overflow-y: auto;
  }
  
  .custom-table {
    width: 100%;
    border-collapse: collapse;
  }
  
  .custom-table th,
  .custom-table td {
    padding: 10px;
    text-align: center;
  }

  .custom-table tr {
    border-bottom: 1px solid rgb(85, 85, 85);
  }
  
  .custom-table tr:not(:last-child) td {
    border: none;
  }

  @media only screen and (max-width: 420px) {
    .table-container {
      margin: 20px;
      max-height: 200px;
      overflow-y: auto;
    }
  }
  </style>
  